# Generated by Django 3.2.3 on 2021-06-04 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stickysticky', '0003_auto_20210604_2056'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Doctor',
            new_name='Sticky2',
        ),
    ]
